### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by rimaille** [Optiroc/BRRtools#1]
Hi, i got a build error on brrtools when building the full toolchain for libSFX :

make[1]: Entering directory '/home/remy/mes_docs/snes/dev/libSFX/tools/brrtools'
mkdir: création du répertoire '.build/'
gcc --std=c99 -Wall -O3 -c src/brr.c -o .build/brr.o
mkdir: création du répertoire 'bin/'
gcc --std=c99 -Wall -O3 src/brr_decoder.c .build/brr.o -o bin/brr_decoder
/tmp/ccFuUiSm.o : Dans la fonction « main » :
brr_decoder.c:(.text.startup+0x1c1) : référence indéfinie vers « ceil »
.build/brr.o : Dans la fonction « print_note_info » :
brr.c:(.text+0xf2) : référence indéfinie vers « log2 »
brr.c:(.text+0x158) : référence indéfinie vers « round »
collect2: erreur : ld a retourné 1 code d'état d'exécution
make[1]: *** [Makefile:13: bin/brr_decoder] Error 1
make[1]: Leaving directory '/home/remy/mes_docs/snes/dev/libSFX/tools/brrtools'
make: *** [Makefile:17: brrtools] Error 2

Same linking error when trying to build brr_encoder.
Can you help me ? Thanks, and sorry if it's my fault (dependency ?).
I'm using GNU make 4.2.1 and ld (GNU binutils) 2.28.0.20170322 on up to date archlinux.

**Comment by Optiroc** [comment]
Hi! I pushed a fix that I think should solve the issue.

(Added `-lm` which should link the math library where `ceil()` lives. Not necessary on my setup (clang/macOS) which is why I didn't catch it. Please report if it works for you now!)

**Comment by rimaille** [comment]
Thanks a lot Optiroc, sorry for my poor programming language, i could have solved it alone...
I'm interested in all that is snes developement related, and i plan to learn a lot on this.

Anyway, it works great, brrtools build is complete ;)

**Comment by Optiroc** [comment]
No problem! Can you build the examples in `libSFX/examples/` now? I'm not sure if I've had linux users build the toolchain without modifications.
