### ISSUE TITLE
brr_encoder hard wrapping when using -g or -rb

### ISSUE THREAD

**Issue by jimbo1qaz** [Optiroc/BRRtools#2]
In `brr_encoder `, anti-Gaussian prefiltering and bandlimited interpolation tend to increase peak levels, resulting in clipping. Since this program uses signed shorts to store intermediate waveforms, these wrap instead of clipping, ruining the output.

I have a branch which redefines `pcm_t` to `signed int`, removes hard-coded "short has width 2" multiplies from malloc calls, and fixes the type of `samples_antialiased` to `pcm_t`. I didn't adapt brr_decoder or spc_decoder to 32-bit samples yet, and I assume they crash.

**Comment by Optiroc** [comment]
👍
